CREATE SCHEMA IF NOT EXISTS news;

CREATE TABLE IF NOT EXISTS news.feeds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    url TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS news.articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_id BIGINT NOT NULL REFERENCES news.feeds(id),
    url TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    source TEXT NOT NULL,
    category TEXT NOT NULL,
    published_at TEXT,
    fetched_at TEXT NOT NULL,
    raw_excerpt TEXT,
    extracted_text TEXT,
    extraction_ok INTEGER NOT NULL DEFAULT 0,
    summary_facts TEXT,
    summary_impact TEXT,
    summary_status TEXT NOT NULL DEFAULT 'pending'
);

CREATE INDEX IF NOT EXISTS idx_articles_published ON news.articles(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_category ON news.articles(category);

CREATE TABLE IF NOT EXISTS news.preferences (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    selected_categories TEXT NOT NULL,
    onboarded INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE news.feeds ENABLE ROW LEVEL SECURITY;
ALTER TABLE news.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE news.preferences ENABLE ROW LEVEL SECURITY;
